In [1]:
import numpy as np

Data tupes

In [2]:


arr = np.array(['app','bana', 'cat'])

print(arr.dtype)

<U4


In [4]:
arr = np.array([1,2,4,5])

print(arr.dtype)

int64


In [5]:
arr = np.array([1.0, 2.3, 4.8, 5])

print(arr.dtype)

float64


In [8]:
arr = np.array(["A", "B", "C"])

print(arr.dtype)

<U1


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='f') #int, float, S, bool

print(arr)

print(arr.dtype)

[1. 2. 3. 4.]
float32


The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [35]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1, 0.0])


newarr = arr.astype('bool') #int float or f, bool, b

print(newarr)
print(newarr.dtype)


print(newarr.astype('f'))

[ True  True  True False]
bool
[1. 1. 1. 0.]


Copy vs View


In [36]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [37]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [42]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()  #copies all the elements and create new obj
y = arr.view()  #references the original obj

z = arr
# z = arr.copy()

print(x.base)
print(y.base)

print(z.base)

z[0] = 45

print(x)
print(z)

None
[1 2 3 4 5]
None
[1 2 3 4 5]
[45  2  3  4  5]


ndim

In [53]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [47]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr


array([[[[[1, 2, 3, 4]]]]])

In [52]:

arr1 = np.zeros(dtype=float, shape=(2,4,3))
arr1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
tu = np.array([1,2,5])

print(tu)   #numpy.array objects

print(list(tu))  # converting numpy.array objects to list not values.

tup = tuple(tu.tolist())
print(tup)

# print(tup.__sizeof__)

# print(list(tup))

lis = tu.tolist()
print(lis)

[1 2 5]
[np.int64(1), np.int64(2), np.int64(5)]
(1, 2, 5)
[1, 2, 5]


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = arr.reshape(2, 4)  #only in view

print(x)
print(x.base)


arr[0] = 25

print(x)
print(x.base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[25  2  3  4]
 [ 5  6  7  8]]
[25  2  3  4  5  6  7  8]


Unknown dimentions
* Pass -1 as the value, and NumPy will calculate this number for you.

In [80]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, -1) 

print(newarr)

newarr.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [82]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)

newarr_flat = arr.flatten()
print(newarr_flat)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [87]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]


Iterating


In [3]:
import numpy as np

arr = np.array([1,2,4,5])
for x in arr:
  print(x)

1
2
4
5


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
for x in arr:
    # for y in x:
     print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y, end=" ")


for x in np.nditer(arr):
  print(x, end=" ")

1 2 3 4 5 6 1 2 3 4 5 6 

Iterating Arrays Using nditer()

In [14]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x, end=' ')


1 2 3 4 5 6 7 8 

In [27]:
arr = np.array([1, 2, 3])

# y = arr.view()

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [41]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
  print(x)


1
3
5
7


In [65]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(x for x in np.nditer(arr[:,::2])) #gives an generator obj

for x in np.nditer(arr[:,::2]):
  print(x)

<generator object <genexpr> at 0x00000298F67F2110>
1
3
5
7


Enumerated Iteration Using ndenumerate()

* Enumeration means mentioning sequence number of somethings one by one.
* Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.



In [69]:
x = [(1,2),(4,4),(5,6)]

for x,y in enumerate(x):
    print(x,y)

0 (1, 2)
1 (4, 4)
2 (5, 6)


In [73]:
# arr = np.array([[1, 2, 3],[5,6,7]])
arr = np.array([1, 2, 3,5,6,7])

for idx, x in np.ndenumerate(arr): #arr index, element index
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 5
(4,) 6
(5,) 7


NumPy Joining Array


In [82]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))  # 1D array gives 1D array

# print(type(arr))


print(arr)

[1 2 3 4 5 6]


In [93]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)  # 2D array gives 2D array, with joing the axis 1(col), axis 0(row)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions
* Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)  #2 2D arrays

arr

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [91]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

arr

array([[1, 4],
       [2, 5],
       [3, 6]])

Stacking Along Rows
* NumPy provides a helper function: hstack() to stack along rows.

In [ ]:
arr1 = np.array([[1, 2, 3], [4,5,6]])

arr2 = np.array([[4, 5, 6],[7,8,9]])

arr = np.hstack((arr1, arr2))  # combines and stack the arrays

# arr = np.concat((arr1, arr2))  # combines the arrays

print(arr)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


Stacking Along Columns
* NumPy provides a helper function: vstack()  to stack along columns.

In [100]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [102]:
arr1 = np.array([[1, 2, 3], [4,5,6]])

arr2 = np.array([[4, 5, 6],[7,8,9]])

arr = np.vstack((arr1,arr2))

arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

Stacking Along Height (depth)
* NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [103]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [105]:
arr1 = np.array([[1, 2, 3], [4,5,6]])

arr2 = np.array([[4, 5, 6],[7,8,9]])

arr = np.dstack((arr1, arr2))

arr

array([[[1, 4],
        [2, 5],
        [3, 6]],

       [[4, 7],
        [5, 8],
        [6, 9]]])

Splitting NumPy Arrays
* Splitting is reverse operation of Joining.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

for x in newarr:
    print(type(x), x)


[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'numpy.ndarray'> [1 2]
<class 'numpy.ndarray'> [3 4]
<class 'numpy.ndarray'> [5 6]


Note: The return value is a list containing three arrays.



In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Splitting 2-D Arrays


In [6]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Numpy array searchihng

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)  #returns a tuple

print(x)

(array([3, 5, 6]),)


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


(array([1, 3, 5, 7]),)


In [12]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


1


In [13]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)


2


In [14]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


Sorting

In [15]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


Note: This method returns a copy of the array, leaving the original array unchanged.



In [16]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [17]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sorting 2-D array

In [18]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


Numpy Array Filtering

Getting some elements out of an existing array and creating a new array out of them is called filtering.
* A boolean index list is a list of booleans corresponding to indexes in the array.





In [23]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

newarr

array([41, 43])

In [24]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [25]:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr%2 == 1

newarr = arr[filter_arr]

newarr

array([1, 3, 5, 7])